version: '3'
services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - hh-parser

  webapp:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - hh-parser

networks:
  hh-parser:
