"""status added

Revision ID: b1f0b5353319
Revises: 39639a88cc20
Create Date: 2022-06-15 12:36:53.206126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f0b5353319'
down_revision = '39639a88cc20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'status')
    # ### end Alembic commands ###
